default:

  #
  # Basic
  #
  server:
    port: 8000

  #
  # Log
  #
  log:
    path: playabl-test-server.log

  #
  # Microservice
  #
  microservice:
    basePath: services
    server:
      name: test/playabl/server
      # Add dependencies by uncommenting the line below
      #
      # dependencies: my/other/service/v1

  #
  # Zookeeper
  #
  zookeeper:
    connectionString: localhost:2181
    retry:
      wait: 1000
      count: 3
